articles/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleRebuttalView,
    ArticleCreateView,
    ArticleUpdateView,
)

urlpatterns = [
    path("", ArticleListView.as_view(), name="article_list"),
    path("<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("new/", ArticleCreateView.as_view(), name="article_new"),
    path("edit/<int:pk>", ArticleUpdateView.as_view(), name="article_edit"),
    path("rebuttal/<int:pk>/", ArticleRebuttalView.as_view(), name="article_rebuttal"),
]

newspaper_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path("articles/", include("articles.urls")),
    path("", include("pages.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [path("", HomePageView.as_view(), name="home")]

users/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [path("signup/", SignUpView.as_view(), name="signup")]

articles/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", args=[str(self.id)])


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()

    def __str__(self):
        return f'{self.author.full_name()} on "{self.article}"'


class Rebuttal(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()

    def __str__(self):
        return self.body[:25]

dataparser/models.py
from django.db import models


class NameInput(models.Model):
    raw = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.raw[:25]

    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)  # Call the "real" save() method.

        names = self.raw.split(",")
        # Just for demonstration
        for name in names:
            print(name)

        # Create Name objects
        for name in names:
            Name.objects.create(name=name, source=self)


class Name(models.Model):
    name = models.CharField(max_length=200)
    source = models.ForeignKey(NameInput, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

    def full_name(self):
        return self.last_name + ", " + self.first_name

articles/forms.py
from django.forms.models import inlineformset_factory
from .models import Article, Comment

CommentFormSet = inlineformset_factory(
    Article, Comment, fields=["article", "author", "body"], exclude=[], can_delete=False
)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ("username", "email", "age")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email", "age")

articles/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Article
from .forms import CommentFormSet
from django.contrib.auth.mixins import LoginRequiredMixin


class ArticleListView(ListView):
    model = Article
    template_name = "article_list.html"
    ordering = ["-date"]


class ArticleDetailView(DetailView):
    model = Article
    template_name = "article_detail.html"


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = "article_new.html"
    fields = ["title", "body"]

    def get_context_data(self, **kwargs):
        context = super(ArticleCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context["comment_formset"] = CommentFormSet(self.request.POST)
        else:
            context["comment_formset"] = CommentFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        formset = context["comment_formset"]
        form.instance.author = self.request.user
        if formset.is_valid():
            response = super().form_valid(form)
            formset.instance = self.object
            formset.save()
            return response
        else:
            return super().form_invalid(form)


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    template_name = "article_edit.html"
    fields = ["title", "body"]


class ArticleRebuttalView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = "article_rebuttal.html"

dataparser/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "signup.html"

templates/article_detail.html
{% extends 'base.html' %}

{% block title %}
{{ article.title }}
{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ article.title }}</span> &middot;
        <span class="text-muted">by {{ article.author.full_name }} |
            {{ article.date }}</span>
    </div>
    <div class="card-body">
        {{ article.body }}
    </div>

    <hr>

    <h5>Number of comments: {{ article.comment_set.count }}</h5>

    {% for comment in article.comment_set.all %}
    <p>{{ comment.author }} at {{ comment.date }}: {{ comment.body }}</p>
    {% endfor %}

    <div class="card-footer text-center text-muted">
        <a href="{% url 'article_edit' article.pk %}">Edit</a> | <a href="#">Delete</a>
        {% if user.is_authenticated %} | <a href="{% url 'article_rebuttal' article.pk %}">Rebuttals</a>{% endif %}
    </div>
</div>
<br />
{% endblock content %}

templates/article_edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit article</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update article" />
</form>
{% endblock content %}

templates/article_list.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}
{% for article in object_list %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ article.title }}</span> &middot;
        <span class="text-muted">by {{ article.author.last_name }} |
            {{ article.date }}</span> |
        <a href="{% url 'article_detail' article.pk %}">Article details </a>
    </div>
    <div class="card-body">
        {{ article.body }}
    </div>
    <div class="card-footer text-center text-muted">
        <a href="#">Edit</a> | <a href="#">Delete</a>
    </div>
</div>
<br />
{% endfor %}
{% endblock content %}

templates/article_new.html
{% extends 'base.html' %}

{% block content %}
<h1>New article</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <hr>
  <p>Add some comments:</p>
  {{ comment_formset.as_p }}
  <input type="submit" value="Publish article" />
</form>
{% endblock content %}

templates/article_rebuttal.html
{% extends 'base.html' %}

{% block title %}
{{ article.title }}
{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-header">
        <span class="font-weight-bold">{{ article.title }}</span> &middot;
        <span class="text-muted">by {{ article.author.full_name }} |
            {{ article.date }}</span>
    </div>
    <div class="card-body">
        {{ article.body }}
    </div>

    <hr>

    <h5>Number of comments: {{ article.comment_set.count }}</h5>

    {% for comment in article.comment_set.all %}
    <p>{{ comment.author }} at {{ comment.date }}: {{ comment.body }}</p>
    <ul>
        {% for rebuttal in comment.rebuttal_set.all %}
        <li>{{ rebuttal.author }} @ {{ rebuttal.date }}: {{ rebuttal.body }}</li>
        {% endfor %}
    </ul>

    {% endfor %}

    <div class="card-footer text-center text-muted">
        <a href="#">Edit</a> | <a href="#">Delete</a>
    </div>
</div>
<br />
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Newspaper App{% endblock title %}</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>

  <div class="container">
    <nav>
      {% block login %}
      {% if user.is_authenticated %}
      <p>
        Hi {{ user.username }}!
        <a href="{% url 'logout' %}">Log out</a>.
      </p>
      {% else %}
      <p>
        You are not logged in. <a href=" {% url 'login' %}">Log in</a> or <a href="{% url 'signup' %}">sign up</a>.
      </p>
      {% endif %}
      {% endblock login %}
      {% block nav %}
      <p>
        Oh the places you'll go:
      </p>
      <ul>
        <li>
          <a href="{% url 'home' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'article_list' %}">Article list</a>
        </li>
        <li>
          <a href="{% url 'article_new' %}">Write a new article</a>
        </li>
      </ul>
      {% endblock nav %}

    </nav>
    {% block content %}
    {% endblock content %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<p>This is the home page.</p>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Sign up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Sign Up</button>
</form>
{% endblock content %}